// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.23.0
// source: replication/pb/cluster.proto

package replicationpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClusterControl_Election_FullMethodName        = "/badgertestreplication.ClusterControl/Election"
	ClusterControl_Coordinator_FullMethodName     = "/badgertestreplication.ClusterControl/Coordinator"
	ClusterControl_Heartbeat_FullMethodName       = "/badgertestreplication.ClusterControl/Heartbeat"
	ClusterControl_GetNodeState_FullMethodName    = "/badgertestreplication.ClusterControl/GetNodeState"
	ClusterControl_Cursor_FullMethodName          = "/badgertestreplication.ClusterControl/Cursor"
	ClusterControl_ApplyFrames_FullMethodName     = "/badgertestreplication.ClusterControl/ApplyFrames"
	ClusterControl_InstallSnapshot_FullMethodName = "/badgertestreplication.ClusterControl/InstallSnapshot"
)

// ClusterControlClient is the client API for ClusterControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClusterControlClient interface {
	Election(ctx context.Context, in *ElectionRequest, opts ...grpc.CallOption) (*ElectionResponse, error)
	Coordinator(ctx context.Context, in *CoordinatorRequest, opts ...grpc.CallOption) (*CoordinatorResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	GetNodeState(ctx context.Context, in *GetNodeStateRequest, opts ...grpc.CallOption) (*GetNodeStateResponse, error)
	Cursor(ctx context.Context, in *CursorRequest, opts ...grpc.CallOption) (*CursorResponse, error)
	ApplyFrames(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ApplyFramesRequest, ApplyFramesResponse], error)
	InstallSnapshot(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[InstallSnapshotRequest, InstallSnapshotResponse], error)
}

type clusterControlClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterControlClient(cc grpc.ClientConnInterface) ClusterControlClient {
	return &clusterControlClient{cc}
}

func (c *clusterControlClient) Election(ctx context.Context, in *ElectionRequest, opts ...grpc.CallOption) (*ElectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ElectionResponse)
	err := c.cc.Invoke(ctx, ClusterControl_Election_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterControlClient) Coordinator(ctx context.Context, in *CoordinatorRequest, opts ...grpc.CallOption) (*CoordinatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoordinatorResponse)
	err := c.cc.Invoke(ctx, ClusterControl_Coordinator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterControlClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, ClusterControl_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterControlClient) GetNodeState(ctx context.Context, in *GetNodeStateRequest, opts ...grpc.CallOption) (*GetNodeStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeStateResponse)
	err := c.cc.Invoke(ctx, ClusterControl_GetNodeState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterControlClient) Cursor(ctx context.Context, in *CursorRequest, opts ...grpc.CallOption) (*CursorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CursorResponse)
	err := c.cc.Invoke(ctx, ClusterControl_Cursor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterControlClient) ApplyFrames(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ApplyFramesRequest, ApplyFramesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClusterControl_ServiceDesc.Streams[0], ClusterControl_ApplyFrames_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ApplyFramesRequest, ApplyFramesResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterControl_ApplyFramesClient = grpc.BidiStreamingClient[ApplyFramesRequest, ApplyFramesResponse]

func (c *clusterControlClient) InstallSnapshot(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[InstallSnapshotRequest, InstallSnapshotResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClusterControl_ServiceDesc.Streams[1], ClusterControl_InstallSnapshot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InstallSnapshotRequest, InstallSnapshotResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterControl_InstallSnapshotClient = grpc.ClientStreamingClient[InstallSnapshotRequest, InstallSnapshotResponse]

// ClusterControlServer is the server API for ClusterControl service.
// All implementations must embed UnimplementedClusterControlServer
// for forward compatibility.
type ClusterControlServer interface {
	Election(context.Context, *ElectionRequest) (*ElectionResponse, error)
	Coordinator(context.Context, *CoordinatorRequest) (*CoordinatorResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	GetNodeState(context.Context, *GetNodeStateRequest) (*GetNodeStateResponse, error)
	Cursor(context.Context, *CursorRequest) (*CursorResponse, error)
	ApplyFrames(grpc.BidiStreamingServer[ApplyFramesRequest, ApplyFramesResponse]) error
	InstallSnapshot(grpc.ClientStreamingServer[InstallSnapshotRequest, InstallSnapshotResponse]) error
	mustEmbedUnimplementedClusterControlServer()
}

// UnimplementedClusterControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClusterControlServer struct{}

func (UnimplementedClusterControlServer) Election(context.Context, *ElectionRequest) (*ElectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Election not implemented")
}
func (UnimplementedClusterControlServer) Coordinator(context.Context, *CoordinatorRequest) (*CoordinatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Coordinator not implemented")
}
func (UnimplementedClusterControlServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedClusterControlServer) GetNodeState(context.Context, *GetNodeStateRequest) (*GetNodeStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeState not implemented")
}
func (UnimplementedClusterControlServer) Cursor(context.Context, *CursorRequest) (*CursorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cursor not implemented")
}
func (UnimplementedClusterControlServer) ApplyFrames(grpc.BidiStreamingServer[ApplyFramesRequest, ApplyFramesResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ApplyFrames not implemented")
}
func (UnimplementedClusterControlServer) InstallSnapshot(grpc.ClientStreamingServer[InstallSnapshotRequest, InstallSnapshotResponse]) error {
	return status.Errorf(codes.Unimplemented, "method InstallSnapshot not implemented")
}
func (UnimplementedClusterControlServer) mustEmbedUnimplementedClusterControlServer() {}
func (UnimplementedClusterControlServer) testEmbeddedByValue()                        {}

// UnsafeClusterControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterControlServer will
// result in compilation errors.
type UnsafeClusterControlServer interface {
	mustEmbedUnimplementedClusterControlServer()
}

func RegisterClusterControlServer(s grpc.ServiceRegistrar, srv ClusterControlServer) {
	// If the following call pancis, it indicates UnimplementedClusterControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClusterControl_ServiceDesc, srv)
}

func _ClusterControl_Election_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterControlServer).Election(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterControl_Election_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterControlServer).Election(ctx, req.(*ElectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterControl_Coordinator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoordinatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterControlServer).Coordinator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterControl_Coordinator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterControlServer).Coordinator(ctx, req.(*CoordinatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterControl_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterControlServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterControl_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterControlServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterControl_GetNodeState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterControlServer).GetNodeState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterControl_GetNodeState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterControlServer).GetNodeState(ctx, req.(*GetNodeStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterControl_Cursor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CursorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterControlServer).Cursor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterControl_Cursor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterControlServer).Cursor(ctx, req.(*CursorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterControl_ApplyFrames_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClusterControlServer).ApplyFrames(&grpc.GenericServerStream[ApplyFramesRequest, ApplyFramesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterControl_ApplyFramesServer = grpc.BidiStreamingServer[ApplyFramesRequest, ApplyFramesResponse]

func _ClusterControl_InstallSnapshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClusterControlServer).InstallSnapshot(&grpc.GenericServerStream[InstallSnapshotRequest, InstallSnapshotResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterControl_InstallSnapshotServer = grpc.ClientStreamingServer[InstallSnapshotRequest, InstallSnapshotResponse]

// ClusterControl_ServiceDesc is the grpc.ServiceDesc for ClusterControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "badgertestreplication.ClusterControl",
	HandlerType: (*ClusterControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Election",
			Handler:    _ClusterControl_Election_Handler,
		},
		{
			MethodName: "Coordinator",
			Handler:    _ClusterControl_Coordinator_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _ClusterControl_Heartbeat_Handler,
		},
		{
			MethodName: "GetNodeState",
			Handler:    _ClusterControl_GetNodeState_Handler,
		},
		{
			MethodName: "Cursor",
			Handler:    _ClusterControl_Cursor_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ApplyFrames",
			Handler:       _ClusterControl_ApplyFrames_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "InstallSnapshot",
			Handler:       _ClusterControl_InstallSnapshot_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "replication/pb/cluster.proto",
}
