//
// SPDX-FileCopyrightText: © 2017-2025 Istari Digital, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.0
// source: wal_replication.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WALFrame_Type int32

const (
	WALFrame_UNKNOWN    WALFrame_Type = 0
	WALFrame_ENTRY      WALFrame_Type = 1
	WALFrame_TXN_INTENT WALFrame_Type = 2
	WALFrame_TXN_COMMIT WALFrame_Type = 3
	WALFrame_CHECKPOINT WALFrame_Type = 4
)

// Enum value maps for WALFrame_Type.
var (
	WALFrame_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "ENTRY",
		2: "TXN_INTENT",
		3: "TXN_COMMIT",
		4: "CHECKPOINT",
	}
	WALFrame_Type_value = map[string]int32{
		"UNKNOWN":    0,
		"ENTRY":      1,
		"TXN_INTENT": 2,
		"TXN_COMMIT": 3,
		"CHECKPOINT": 4,
	}
)

func (x WALFrame_Type) Enum() *WALFrame_Type {
	p := new(WALFrame_Type)
	*p = x
	return p
}

func (x WALFrame_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WALFrame_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_wal_replication_proto_enumTypes[0].Descriptor()
}

func (WALFrame_Type) Type() protoreflect.EnumType {
	return &file_wal_replication_proto_enumTypes[0]
}

func (x WALFrame_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WALFrame_Type.Descriptor instead.
func (WALFrame_Type) EnumDescriptor() ([]byte, []int) {
	return file_wal_replication_proto_rawDescGZIP(), []int{1, 0}
}

type WALCursor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fid    uint32 `protobuf:"varint,1,opt,name=fid,proto3" json:"fid,omitempty"`
	Offset uint32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Len    uint32 `protobuf:"varint,3,opt,name=len,proto3" json:"len,omitempty"`
}

func (x *WALCursor) Reset() {
	*x = WALCursor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wal_replication_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WALCursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALCursor) ProtoMessage() {}

func (x *WALCursor) ProtoReflect() protoreflect.Message {
	mi := &file_wal_replication_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALCursor.ProtoReflect.Descriptor instead.
func (*WALCursor) Descriptor() ([]byte, []int) {
	return file_wal_replication_proto_rawDescGZIP(), []int{0}
}

func (x *WALCursor) GetFid() uint32 {
	if x != nil {
		return x.Fid
	}
	return 0
}

func (x *WALCursor) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *WALCursor) GetLen() uint32 {
	if x != nil {
		return x.Len
	}
	return 0
}

type WALFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version uint32        `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Type    WALFrame_Type `protobuf:"varint,2,opt,name=type,proto3,enum=badgerpb4.WALFrame_Type" json:"type,omitempty"`
	Lsn     *WALCursor    `protobuf:"bytes,3,opt,name=lsn,proto3" json:"lsn,omitempty"`
	Key     []byte        `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Value   []byte        `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	// Mirrors badgerpb4.KV.meta encoding (single byte payload).
	Meta []byte `protobuf:"bytes,6,opt,name=meta,proto3" json:"meta,omitempty"`
	// Mirrors badgerpb4.KV.user_meta encoding (single byte payload).
	UserMeta  []byte `protobuf:"bytes,7,opt,name=user_meta,json=userMeta,proto3" json:"user_meta,omitempty"`
	ExpiresAt uint64 `protobuf:"varint,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
}

func (x *WALFrame) Reset() {
	*x = WALFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wal_replication_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WALFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALFrame) ProtoMessage() {}

func (x *WALFrame) ProtoReflect() protoreflect.Message {
	mi := &file_wal_replication_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALFrame.ProtoReflect.Descriptor instead.
func (*WALFrame) Descriptor() ([]byte, []int) {
	return file_wal_replication_proto_rawDescGZIP(), []int{1}
}

func (x *WALFrame) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *WALFrame) GetType() WALFrame_Type {
	if x != nil {
		return x.Type
	}
	return WALFrame_UNKNOWN
}

func (x *WALFrame) GetLsn() *WALCursor {
	if x != nil {
		return x.Lsn
	}
	return nil
}

func (x *WALFrame) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *WALFrame) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *WALFrame) GetMeta() []byte {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *WALFrame) GetUserMeta() []byte {
	if x != nil {
		return x.UserMeta
	}
	return nil
}

func (x *WALFrame) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

var File_wal_replication_proto protoreflect.FileDescriptor

var file_wal_replication_proto_rawDesc = []byte{
	0x0a, 0x15, 0x77, 0x61, 0x6c, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x62, 0x61, 0x64, 0x67, 0x65, 0x72, 0x70,
	0x62, 0x34, 0x22, 0x47, 0x0a, 0x09, 0x57, 0x41, 0x4c, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12,
	0x10, 0x0a, 0x03, 0x66, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x66, 0x69,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x65, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6c, 0x65, 0x6e, 0x22, 0xc2, 0x02, 0x0a, 0x08,
	0x57, 0x41, 0x4c, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x18, 0x2e, 0x62, 0x61, 0x64, 0x67, 0x65, 0x72, 0x70, 0x62, 0x34, 0x2e, 0x57, 0x41, 0x4c,
	0x46, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x26, 0x0a, 0x03, 0x6c, 0x73, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x62, 0x61, 0x64, 0x67, 0x65, 0x72, 0x70, 0x62, 0x34, 0x2e, 0x57, 0x41, 0x4c, 0x43, 0x75, 0x72,
	0x73, 0x6f, 0x72, 0x52, 0x03, 0x6c, 0x73, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x6d, 0x65, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x74,
	0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x74,
	0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x61, 0x74, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x41, 0x74,
	0x22, 0x4e, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x4e, 0x54, 0x52, 0x59, 0x10, 0x01,
	0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x58, 0x4e, 0x5f, 0x49, 0x4e, 0x54, 0x45, 0x4e, 0x54, 0x10, 0x02,
	0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x58, 0x4e, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x49, 0x54, 0x10, 0x03,
	0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x48, 0x45, 0x43, 0x4b, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x10, 0x04,
	0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64,
	0x67, 0x72, 0x61, 0x70, 0x68, 0x2d, 0x69, 0x6f, 0x2f, 0x62, 0x61, 0x64, 0x67, 0x65, 0x72, 0x2f,
	0x76, 0x34, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wal_replication_proto_rawDescOnce sync.Once
	file_wal_replication_proto_rawDescData = file_wal_replication_proto_rawDesc
)

func file_wal_replication_proto_rawDescGZIP() []byte {
	file_wal_replication_proto_rawDescOnce.Do(func() {
		file_wal_replication_proto_rawDescData = protoimpl.X.CompressGZIP(file_wal_replication_proto_rawDescData)
	})
	return file_wal_replication_proto_rawDescData
}

var file_wal_replication_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wal_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_wal_replication_proto_goTypes = []interface{}{
	(WALFrame_Type)(0), // 0: badgerpb4.WALFrame.Type
	(*WALCursor)(nil),  // 1: badgerpb4.WALCursor
	(*WALFrame)(nil),   // 2: badgerpb4.WALFrame
}
var file_wal_replication_proto_depIdxs = []int32{
	0, // 0: badgerpb4.WALFrame.type:type_name -> badgerpb4.WALFrame.Type
	1, // 1: badgerpb4.WALFrame.lsn:type_name -> badgerpb4.WALCursor
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_wal_replication_proto_init() }
func file_wal_replication_proto_init() {
	if File_wal_replication_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wal_replication_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WALCursor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wal_replication_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WALFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wal_replication_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wal_replication_proto_goTypes,
		DependencyIndexes: file_wal_replication_proto_depIdxs,
		EnumInfos:         file_wal_replication_proto_enumTypes,
		MessageInfos:      file_wal_replication_proto_msgTypes,
	}.Build()
	File_wal_replication_proto = out.File
	file_wal_replication_proto_rawDesc = nil
	file_wal_replication_proto_goTypes = nil
	file_wal_replication_proto_depIdxs = nil
}
